In [5]:
import numpy as np  #try install numpy using pip: pip install numpy

In [6]:
a=np.array([1,2,3,4,5]) #one-dimensional array

In [8]:
a

array([1, 2, 3, 4, 5])

In [10]:
a.ndim  #dimension of array

1

In [19]:
b=np.array([[1,2,3],[4,5,6]]) #two-dimensional array

In [20]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
b.ndim

2

In [22]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]]) #three-dimensional array

In [25]:
c.ndim

2

# Zeros nd one's func

In [27]:
d=np.zeros(10)

In [30]:
d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
print(d.dtype) #data type of the array

float64


In [35]:
print(d.reshape(5,2)) #5 rows and 2 columns(reshaping)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [37]:
e=np.zeros(15,dtype=int) #setting data type for zero func

In [39]:
e

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
f=np.zeros((4,6),int) #2-dim numpy array

In [43]:
f

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [46]:
f.dtype

dtype('int64')

In [48]:
g=np.zeros((3,5,2)) # 3-array 5-row 2-column

In [50]:
g

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [52]:
g.ndim

3

# one's func

In [53]:
h=np.ones(10)

In [55]:
h

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [59]:
i=np.ones((4,2,6),int)

In [61]:
i

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

# arry func

In [62]:
var=np.array([77,99,88])

In [64]:
var

array([77, 99, 88])

In [66]:
type(var)

numpy.ndarray

In [68]:
var.argmin() #returning the minimum value'th position

0

In [70]:
var.argmax() #returning the maximum value'th position

1

In [72]:
var.dtype

dtype('int64')

In [74]:
var[2] #indexing

88

In [78]:
var[0:] #slicing

array([77, 99, 88])

In [80]:
var[0:1]

array([77])

In [82]:
var[0:2]

array([77, 99])

In [84]:
var[0:3]

array([77, 99, 88])

In [86]:
var[2]=105

In [88]:
var

array([ 77,  99, 105])

Reshape and Resize func

In [91]:
j=np.arange(12)

j

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [93]:
j.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [108]:
j.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [110]:
j.sum() #sum of the array

66

In [111]:
j.max() #maximum of number

11

In [112]:
j.min() #minimum of number

0

In [113]:
k=125

In [115]:
np.sqrt(k) 

11.180339887498949

In [116]:
np.log(k)

4.8283137373023015